Bad-usb BLE (standalone app)
ClaraCrazy/Flipper-Xtreme pull request #116
Opened 2023-01-27 11:20 UTC by yocvito

Hi, I come here with a modification I made to flipper-Xtreme to add a basic bad BLE app. This is just the bad-USB app modified to work with BLE with a few modifications. 

# What have been done 

- Modified bad usb script thread to init/deinit bluetooth
- Modified bt, hal and gap layers to allow modifying Bt Adv name and Bt MAC address

# What remains to do

- Integrate app to bad-USB
- Remove pin verif procedure
- Spoof another Bt appareance (if possible)

-----
# For the reviewer

I know I didn't follow the development rules or some concepts about flipper dev. I hope you will point it out for me to fix it.

- [x] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

2023-01-27 11:43 UTC, ClaraCrazy commented on firmware/targets/f7/api_symbols.csv
> +Function,-,canvas_commit,void,Canvas*
why?

2023-01-27 11:43 UTC, ClaraCrazy commented on firmware/targets/f7/api_symbols.csv
> +Function,-,canvas_reset,void,Canvas*
same here, why?

2023-01-27 11:49 UTC, ClaraCrazy requested changes
See comments.

Also yes, this really should be integrated into BadUSB with a toggle. idk if @Willy-JL wants to help you with that, or maybe @floriangrousset but I doubt he has the time rn

2023-01-27 11:49 UTC, ClaraCrazy commented on firmware/targets/f7/api_symbols.csv
> +Function,?,furi_hal_bt_hid_kb_free_slots,_Bool,uint8_t
all of these `?` need to be `+` or `-`, depending on your needs.

2023-01-27 11:49 UTC, ClaraCrazy commented on firmware/targets/f7/api_symbols.csv
> +Function,-,canvas_commit,void,Canvas*
?

2023-01-27 11:49 UTC, ClaraCrazy commented on firmware/targets/f7/api_symbols.csv
> +Function,-,canvas_reset,void,Canvas*
?

2023-01-28 07:06 UTC, Willy-JL commented
I have moved almost all the current code to the Bad USB app. There is now a toggle for which mode to use in the config pane of the app. From my testing it seems stable, but do let me know if you find issues with it since I had to use some workarounds to get the toggle to hide and show the BT-specific options on demand (namely having it be actually split in 2 different interfaces and switch between them when the option is toggled).

For now the toggle does not affect the actual functionality of Bad USB, it still works only over usb. The only code that remains to be ported over is actually the bt related code, in `bad_ble_script.c` to `bad_usb_script.c`. I have ported the new functions and definitions over and commented them out in `bad_ble_script.c`, along with the ones that were left unchanged. What remains to be done is to port the un-commented ones from `bad_ble_script.c` into Bad USB adding a check for whether to use USB or BT APIs to each of them. I did notice that these usually don't have access to the app/script context, so they wouldn't have direct access to the `is_bluetooth` variable I implemented on `BadUsbApp`; one possible solution that comes to mind is storing this value at script runtime in a module level variable, and having the APIs check that.

2023-01-29 03:36 UTC, Willy-JL commented
Moved all the other code to the Bad USB app, should work properly now. One thing I noticed is `ducky_numlock_on()` still uses `furi_hal_hid_get_led_state()`, so that could cause issues... other than that I would say the first point in "What remains to do" is now done :smile:

2023-01-29 04:45 UTC, desktopsetup commented
just cucked my wife feels good

2023-01-29 20:44 UTC, Willy-JL commented
Fixed the keyboard layouts to be synced between usb and bt mode, and to reapply before starting a script since bt liked to have them reset now and then. Works perfectly so far for me. The issue with `furi_hal_hid_get_led_state()` and `ducky_numlock_on()` remains, so unless a bt equivalent of that is added the ALTSTRING and ALTCHAR commands will probably not work that well, if at all.

2023-01-30 12:38 UTC, yocvito reviewed
I added a check in gap layer to check for pairing method, and changes needed config to remove pin verif at pairing. I also modified bt init/deinit in bad usb script worker to modify the Bt HID profile pairing method at runtime.

2023-02-12 01:20 UTC, merged