Added genie protocol.
ClaraCrazy/Flipper-Xtreme pull request #475
Opened 2023-12-04 14:39 UTC by trivera90

# What's new

-Garage door genie protocol added.
-Credits to Derek Jamison aka codeallnight.

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

2023-12-08 21:12 UTC, Willy-JL commented
doesn't this also need an extra app and a gpio rig to be useful? is there any practical use by just including this protocol as is?

2023-12-12 22:40 UTC, trivera90 commented
I believe it would identify the protocol when scanning frequencies, although it wouldn't be able to play it with out the keys file. I use it with my garage door using the keys file that he provides without using the app. Maybe include the app as well? I couldn't get it to work though.

2023-12-30 16:10 UTC, Hamadatail commented
hey i have tried to download and install the latest firmware, how ever its keep failing

2023-12-30 16:29 UTC, N-coder82 commented
> hey i have tried to download and install the latest firmware, how ever its keep failing 

Please make a new issue, don't hijacker's other issues.

2024-01-20 14:17 UTC, celsow approved these changes

2024-02-26 03:27 UTC, Bendeneton10 requested changes
Espero aprovacion

2024-03-11 01:08 UTC, xMasterX commented
Protocol doesn't have full encryption support, it requires external app that will collect "hop" parts from the keyfob by spamming the real keyfob button and recording sent keys as is, which is ok as demo, but is not usable for regular usage, and makes no sense to add only half of the protocol

If you want to implement decoder only, remove all unused code and undraft the PR
Thanks

2025-02-26 20:21 UTC, closed without merging